install:
  - choco install dart-sdk
  - ps: refreshenv
  - refreshenv
  - set DART_DIR=c:\tools\dart-sdk\bin
  - set PUB_EXECUTABLE=pub.bat
  - ps: pwd
  - pub get

build: off

test_script:
  - pub run test
