install:
  - choco install dart-sdk
  - ps: refreshenv
  - refreshenv
  - set DART_DIR=c:\tools\dart-sdk\bin
  - set PUB_EXECUTABLE=pub.bat
  - ps: pwd
  - pub get

build: off

test_script:
  # TODO(tvolkert): Enable testing of LocalFileSystem
  - pub run test test\chroot_test.dart
  - pub run test test\memory_test.dart
  - pub run test test\recording_test.dart
  - pub run test test\replay_test.dart
  - pub run test test\utils_test.dart
